import type { Metadata } from 'next';
import '../../globals.css';

export const metadata: Metadata = {
  title: 'BookWorm',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex-1 flex flex-col">
      <main className="flex-1 p-8 lg:p-16 pt-8">{children}</main>
    </div>
  );
}
