import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import SessionProvider from '@/components/auth/SessionProvider';
import Sidebar from '@/components/layout/Sidebar';
import Topbar from '@/components/layout/TopBar';
import { getUserSession } from '@/lib/session';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'BookWorm',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getUserSession();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex min-h-screen`}
      >
        <SessionProvider session={session}>
          {/* <Sidebar /> */}
          <div className="flex-1 flex flex-col bg-[#30313E] text-white">
            <Topbar />
            <main className="flex-1 p-16 pt-8">{children}</main>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
