export const COUNTRIES = [
  { value: "pl", label: "Polska", icon: "🇵🇱", meta: "(pl)" },
  { value: "de", label: "Niemcy", icon: "🇩🇪", meta: "(de)" },
  { value: "us", label: "Stany Zjednoczone", icon: "🇺🇸", meta: "(us)" },
  { value: "gb", label: "Wielka Brytania", icon: "🇬🇧", meta: "(gb)" },
  { value: "fr", label: "Francja", icon: "🇫🇷", meta: "(fr)" },
  { value: "es", label: "Hiszpania", icon: "🇪🇸", meta: "(es)" },
  { value: "it", label: "Włochy", icon: "🇮🇹", meta: "(it)" },
  { value: "ua", label: "Ukraina", icon: "🇺🇦", meta: "(ua)" },
  { value: "cz", label: "Czechy", icon: "🇨🇿", meta: "(cz)" },
  { value: "sk", label: "Słowacja", icon: "🇸🇰", meta: "(sk)" },
  { value: "ru", label: "Rosja", icon: "🇷🇺", meta: "(ru)" },
  { value: "cn", label: "Chiny", icon: "🇨🇳", meta: "(cn)" },
  { value: "jp", label: "Japonia", icon: "🇯🇵", meta: "(jp)" },
  { value: "kr", label: "Korea Południowa", icon: "🇰🇷", meta: "(kr)" },
  { value: "br", label: "Brazylia", icon: "🇧🇷", meta: "(br)" },
  { value: "ar", label: "Argentyna", icon: "🇦🇷", meta: "(ar)" },
  { value: "ca", label: "Kanada", icon: "🇨🇦", meta: "(ca)" },
  { value: "au", label: "Australia", icon: "🇦🇺", meta: "(au)" },
  { value: "se", label: "Szwecja", icon: "🇸🇪", meta: "(se)" },
  { value: "no", label: "Norwegia", icon: "🇳🇴", meta: "(no)" },
  { value: "fi", label: "Finlandia", icon: "🇫🇮", meta: "(fi)" },
  { value: "dk", label: "Dania", icon: "🇩🇰", meta: "(dk)" },
  { value: "nl", label: "Holandia", icon: "🇳🇱", meta: "(nl)" },
  { value: "be", label: "Belgia", icon: "🇧🇪", meta: "(be)" },
  { value: "ch", label: "Szwajcaria", icon: "🇨🇭", meta: "(ch)" },
  { value: "at", label: "Austria", icon: "🇦🇹", meta: "(at)" },
  { value: "gr", label: "Grecja", icon: "🇬🇷", meta: "(gr)" },
  { value: "tr", label: "Turcja", icon: "🇹🇷", meta: "(tr)" },
  { value: "hu", label: "Węgry", icon: "🇭🇺", meta: "(hu)" },
  { value: "ro", label: "Rumunia", icon: "🇷🇴", meta: "(ro)" },
  { value: "bg", label: "Bułgaria", icon: "🇧🇬", meta: "(bg)" },
  { value: "pt", label: "Portugalia", icon: "🇵🇹", meta: "(pt)" },
  { value: "ie", label: "Irlandia", icon: "🇮🇪", meta: "(ie)" },
  { value: "il", label: "Izrael", icon: "🇮🇱", meta: "(il)" },
] as const;

export type CountryCode = (typeof COUNTRIES)[number]["value"];
