export const GENRE_LABELS = {
  fantasy: "Fantastyka",
  science_fiction: "Science Fiction",
  thriller: "Thriller",
  romance: "Romans",
  non_fiction: "Literatura faktu",
  horror: "Horror",
  mystery: "Tajemnica",
  history: "Historia",
  biography: "Biografia",
  poetry: "Poetryka",
  drama: "Dramat",
  adventure: "Przygodowa",
  classics: "Klasyka",
  children: "Dla dzieci",
  young_adult: "Młodzieżowa",
  self_help: "Poradniki",
  health: "Zdrowie",
  technology: "Technologia",
  philosophy: "Filozofia",
  religion: "Religia",
  art: "Sztuka",
  travel: "Podróże",
  satire: "Satira",
  gothic: "Gotyk",
  dystopia: "Dystopia",
  memoir: "Pamiętnik",
  crime: "Kryminał",
  detective: "Detektywistyczna",
  essay: "Esej",
  humor: "Humor",
  cooking: "Kucharska",
  business: "Biznes",
  education: "Edukacja",
  psychology: "Psychologia",
  politics: "Polityka",
  sport: "Sport",
  true_crime: "Prawdziwe zbrodnie",
  fairy_tales: "Baśnie",
  western: "Western",
  lgbtq: "LGBTQ+",
  culture: "Kultura",
  comics: "Komiksy",
  graphic_novel: "Powieść graficzna",
  essays: "Eseje",
  literary_fiction: "Literatura piękna",
  spirituality: "Duchowość",
  environment: "Ekologia",
  music: "Muzyka",
  classic_fiction: "Klasyczna literatura",
  contemporary_fiction: "Współczesna literatura",
  urban_fantasy: "Miejska fantastyka",
  historical_fiction: "Fikcja historyczna",
  magical_realism: "Realizm magiczny",
  short_stories: "Opowiadania",
  fanfiction: "Fanfiction",
  science: "Nauka",
  astronomy: "Astronomia",
  mathematics: "Matematyka",
  economics: "Ekonomia",
  parenting: "Rodzicielstwo",
  mindfulness: "Uważność",
  productivity: "Produktywność",
  personal_development: "Rozwój osobisty",
  anthropology: "Antropologia",
  sociology: "Socjologia",
  gender_studies: "Studia nad płcią",
  race_and_ethnicity: "Rasa i tożsamość etniczna",
  design: "Design",
  photography: "Fotografia",
  architecture: "Architektura",
  fashion: "Moda",
  gamebook: "Książka paragrafowa",
  zines: "Ziny",
  mythology: "Mitologia",
  folklore: "Folklor",
  autobiography: "Autobiografia",
  animals: "Zwierzęta",
  language: "Języki i językoznawstwo",
  reportage: "Reportaż",
  popular_science: "Popularnonaukowa",
} as Record<string, string>;
