import { Genre } from "@prisma/client";

const DEFAULT_GENRE_COLOR = "bg-slate-500";

export const GENRE_COLOR_MAP: Record<Genre["slug"], string> = {
  fantasy: "bg-purple-500 text-white",
  "science-fiction": "bg-blue-600 text-white",
  thriller: "bg-amber-600 text-white",
  romance: "bg-pink-500 text-white",
  "non-fiction": "bg-emerald-600 text-white",
  horror: "bg-red-700 text-white",
  mystery: "bg-indigo-600 text-white",
  history: "bg-stone-600 text-white",
  biography: "bg-teal-600 text-white",
  poetry: "bg-fuchsia-600 text-white",
  drama: "bg-rose-700 text-white",
  adventure: "bg-orange-600 text-white",
  classics: "bg-slate-700 text-white",
  children: "bg-yellow-400 text-slate-900",
  "young-adult": "bg-lime-600 text-white",
  "self-help": "bg-green-600 text-white",
  health: "bg-emerald-500 text-white",
  technology: "bg-cyan-600 text-white",
  philosophy: "bg-zinc-700 text-white",
  religion: "bg-violet-700 text-white",
  art: "bg-pink-600 text-white",
  travel: "bg-sky-500 text-white",
  satire: "bg-amber-500 text-slate-900",
  gothic: "bg-neutral-800 text-white",
  fashion: "bg-fuchsia-500 text-white",
  gamebook: "bg-indigo-500 text-white",
  zines: "bg-lime-500 text-slate-900",
  mythology: "bg-violet-600 text-white",
  folklore: "bg-amber-700 text-white",
  autobiography: "bg-teal-700 text-white",
  animals: "bg-green-700 text-white",
  language: "bg-sky-700 text-white",
  reportage: "bg-stone-700 text-white",
  "popular-science": "bg-cyan-700 text-white",
  dystopia: "bg-slate-800 text-white",
  memoir: "bg-teal-500 text-white",
  crime: "bg-red-600 text-white",
  detective: "bg-indigo-700 text-white",
  essay: "bg-zinc-600 text-white",
  humor: "bg-yellow-500 text-slate-900",
  cooking: "bg-orange-500 text-white",
  business: "bg-emerald-700 text-white",
  education: "bg-blue-700 text-white",
  psychology: "bg-violet-500 text-white",
  politics: "bg-red-800 text-white",
  sport: "bg-lime-700 text-white",
  "true-crime": "bg-rose-800 text-white",
  "fairy-tales": "bg-pink-400 text-slate-900",
  western: "bg-amber-800 text-white",
  lgbtq: "bg-fuchsia-700 text-white",
  culture: "bg-rose-600 text-white",
  comics: "bg-yellow-400 text-slate-900",
  "graphic-novel": "bg-yellow-600 text-slate-900",
  essays: "bg-zinc-700 text-white",
  "literary-fiction": "bg-slate-600 text-white",
  spirituality: "bg-violet-500 text-white",
  environment: "bg-green-700 text-white",
  music: "bg-purple-600 text-white",
  "classic-fiction": "bg-slate-700 text-white",
  "contemporary-fiction": "bg-slate-500 text-white",
  "urban-fantasy": "bg-purple-700 text-white",
  "historical-fiction": "bg-stone-700 text-white",
  "magical-realism": "bg-fuchsia-700 text-white",
  "short-stories": "bg-sky-600 text-white",
  fanfiction: "bg-pink-700 text-white",
  science: "bg-cyan-500 text-white",
  astronomy: "bg-indigo-800 text-white",
  mathematics: "bg-blue-800 text-white",
  economics: "bg-emerald-800 text-white",
  parenting: "bg-lime-600 text-white",
  mindfulness: "bg-teal-500 text-white",
  productivity: "bg-blue-600 text-white",
  "personal-development": "bg-green-600 text-white",
  anthropology: "bg-stone-600 text-white",
  sociology: "bg-stone-700 text-white",
  "gender-studies": "bg-fuchsia-800 text-white",
  "race-and-ethnicity": "bg-rose-700 text-white",
  design: "bg-fuchsia-600 text-white",
  photography: "bg-slate-800 text-white",
  architecture: "bg-stone-800 text-white",
  "post-apocalyptic": "bg-neutral-900 text-white",
  "space-opera": "bg-indigo-700 text-white",
  cyberpunk: "bg-cyan-700 text-white",
  steampunk: "bg-amber-700 text-white",
  "military-sci-fi": "bg-slate-800 text-white",
  romantasy: "bg-pink-600 text-white",
  "cozy-mystery": "bg-amber-400 text-slate-900",
  "historical-romance": "bg-rose-500 text-white",
  "personal-finance": "bg-emerald-600 text-white",
  "domestic-fiction": "bg-rose-600 text-white",
} as const;

export function getGenreColor(genre: Genre["slug"]): string {
  return (
    GENRE_COLOR_MAP[genre as keyof typeof GENRE_COLOR_MAP] ??
    DEFAULT_GENRE_COLOR
  );
}
