export const genreColorMap: Record<string, string> = {
  FANTASY: 'bg-purple-500',
  SCIENCE_FICTION: 'bg-blue-600',
  THRILLER: 'bg-red-700',
  ROMANCE: 'bg-pink-400',
  NON_FICTION: 'bg-green-600',
  HORROR: 'bg-gray-800',
  MYSTERY: 'bg-indigo-600',
  HISTORY: 'bg-yellow-600',
  BIOGRAPHY: 'bg-amber-500',
  POETRY: 'bg-pink-600',
  DRAMA: 'bg-red-500',
  ADVENTURE: 'bg-orange-500',
  CLASSICS: 'bg-gray-600',
  CHILDREN: 'bg-rose-400',
  YOUNG_ADULT: 'bg-violet-500',
  SELF_HELP: 'bg-teal-500',
  HEALTH: 'bg-green-400',
  TECHNOLOGY: 'bg-cyan-600',
  PHILOSOPHY: 'bg-purple-700',
  RELIGION: 'bg-yellow-400',
  ART: 'bg-red-400',
  TRAVEL: 'bg-blue-400',
  SATIRE: 'bg-pink-700',
  GOTHIC: 'bg-gray-900',
  DYSTOPIA: 'bg-red-900',
  MEMOIR: 'bg-lime-500',
  CRIME: 'bg-red-600',
  DETECTIVE: 'bg-indigo-700',
  ESSAY: 'bg-gray-500',
  HUMOR: 'bg-yellow-300',
  COOKING: 'bg-orange-600',
  BUSINESS: 'bg-blue-700',
  EDUCATION: 'bg-green-500',
  PSYCHOLOGY: 'bg-purple-400',
  POLITICS: 'bg-red-800',
  SPORT: 'bg-teal-600',
  TRUE_CRIME: 'bg-red-900',
  FAIRY_TALES: 'bg-pink-500',
  WESTERN: 'bg-yellow-700',
  LGBTQ: 'bg-pink-600',
  CULTURE: 'bg-indigo-500',
  COMICS: 'bg-red-400',
  GRAPHIC_NOVEL: 'bg-purple-600',
  ESSAYS: 'bg-gray-600',
  LITERARY_FICTION: 'bg-blue-500',
  SPIRITUALITY: 'bg-green-700',
  ENVIRONMENT: 'bg-lime-600',
  MUSIC: 'bg-pink-500',
  CLASSIC_FICTION: 'bg-gray-700',
  CONTEMPORARY_FICTION: 'bg-cyan-500',
};

export function getColor(genre: string) {
  return genreColorMap[genre];
}
