import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import SessionProvider from '@/components/SessionProvider';
import { getServerSession } from 'next-auth';
import Sidebar from '@/components/Sidebar';
import Topbar from '@/components/TopBar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  console.log('session', session?.user?.name);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen`}
      >
        <SessionProvider session={session}>
          <Sidebar />
          <div className="flex-1 flex flex-col bg-[#30313E] text-white">
            <Topbar />
            <main className="flex-1 overflow-auto p-6">{children}</main>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
