-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "GenreSlug" ADD VALUE 'URBAN_FANTASY';
ALTER TYPE "GenreSlug" ADD VALUE 'HISTORICAL_FICTION';
ALTER TYPE "GenreSlug" ADD VALUE 'MAGICAL_REALISM';
ALTER TYPE "GenreSlug" ADD VALUE 'SHORT_STORIES';
ALTER TYPE "GenreSlug" ADD VALUE 'FANFICTION';
ALTER TYPE "GenreSlug" ADD VALUE 'SCIENCE';
ALTER TYPE "GenreSlug" ADD VALUE 'ASTRONOMY';
ALTER TYPE "GenreSlug" ADD VALUE 'MATHEMATICS';
ALTER TYPE "GenreSlug" ADD VALUE 'ECONOMICS';
ALTER TYPE "GenreSlug" ADD VALUE 'PARENTING';
ALTER TYPE "GenreSlug" ADD VALUE 'MINDFULNESS';
ALTER TYPE "GenreSlug" ADD VALUE 'PRODUCTIVITY';
ALTER TYPE "GenreSlug" ADD VALUE 'PERSONAL_DEVELOPMENT';
ALTER TYPE "GenreSlug" ADD VALUE 'ANTHROPOLOGY';
ALTER TYPE "GenreSlug" ADD VALUE 'SOCIOLOGY';
ALTER TYPE "GenreSlug" ADD VALUE 'GENDER_STUDIES';
ALTER TYPE "GenreSlug" ADD VALUE 'RACE_AND_ETHNICITY';
ALTER TYPE "GenreSlug" ADD VALUE 'DESIGN';
ALTER TYPE "GenreSlug" ADD VALUE 'PHOTOGRAPHY';
ALTER TYPE "GenreSlug" ADD VALUE 'ARCHITECTURE';
ALTER TYPE "GenreSlug" ADD VALUE 'FASHION';
ALTER TYPE "GenreSlug" ADD VALUE 'GAMEBOOK';
ALTER TYPE "GenreSlug" ADD VALUE 'ZINES';
ALTER TYPE "GenreSlug" ADD VALUE 'MYTHOLOGY';
ALTER TYPE "GenreSlug" ADD VALUE 'FOLKLORE';
ALTER TYPE "GenreSlug" ADD VALUE 'AUTOBIOGRAPHY';
ALTER TYPE "GenreSlug" ADD VALUE 'ANIMALS';
ALTER TYPE "GenreSlug" ADD VALUE 'LANGUAGE';
